### ISSUE TITLE
i compile c example and get error  

### ISSUE THREAD

**Issue by bellcat2008** [fpj/zookeeper-book-example#1]
[root@JACKY c]# gcc -I/Project/works/Study/zookeeper-3.4.5/src/c/include -I/Project/works/Study/zookeeper-3.4.5/src/c/generated -DTHREADED -L/usr/local/lib -l zookeeper_mt master.c
In file included from master.h:34,
                 from master.c:19:
log.h:43: error: expected ')' before 'callback'
In file included from master.c:19:
master.h: In function 'rc2string':
master.h:191: error: 'ZNEWCONFIGNOQUORUM' undeclared (first use in this function)
master.h:191: error: (Each undeclared identifier is reported only once
master.h:191: error: for each function it appears in.)
master.h:194: error: 'ZRECONFIGINPROGRESS' undeclared (first use in this function)
master.c: In function 'main_watcher':
master.c:236: error: 'ZOO_NOTCONNECTED_STATE' undeclared (first use in this function)

------------------------------------------------------------------------------
i  fllowed your  instruction    in  README.txt   for   C and get the  above  errors  .
could you help me solve the above errors? thx vey much.

**Comment by fpj** [comment]
Hi there!

> master.h:191: error: 'ZNEWCONFIGNOQUORUM' undeclared (first use in this function)
> master.h:191: error: (Each undeclared identifier is reported only once
> master.h:191: error: for each function it appears in.)
> master.h:194: error: 'ZRECONFIGINPROGRESS' undeclared (first use in this function)

these constants indicate that you're using the 3.5 branch or trunk, while the example of the example here was done on the 3.4 branch.

**Comment by bellcat2008** [comment]
i do not know how to use git cmd to get the branch 3.4. so I
1. download  from Download ZIP    and  get   zookeeper-branch-3.4.zip
2.  follow the instruction of   zookeeper-branch-3.4/src/c/README.  to compile zookeeper
2.1  ant compile_jute
2.2  [root@JACKY c]# pwd
/Project/works/Study/zookeeper-branch-3.4/src/c
[root@JACKY c]#  ACLOCAL="aclocal -I /usr/local/share/aclocal" autoreconf -if
2.3 ./configure   make 
make install
3. compile   your  example  
[root@JACKY c]# gcc -I/Project/works/Study/zookeeper-branch-3.4/src/c/include -I/Project/works/Study/zookeeper-branch-3.4/src/c/generated -DTHREADED -L/usr/local/lib -l zookeeper_mt master.c

In file included from master.h:33,
                 from master.c:19:
log.h:43: error: expected ')' before 'callback'
In file included from master.c:19:
master.h: In function 'rc2string':
master.h:189: error: 'ZNEWCONFIGNOQUORUM' undeclared (first use in this function)
master.h:189: error: (Each undeclared identifier is reported only once
master.h:189: error: for each function it appears in.)
master.h:192: error: 'ZRECONFIGINPROGRESS' undeclared (first use in this function)
master.c: In function 'main_watcher':
master.c:236: error: 'ZOO_NOTCONNECTED_STATE' undeclared (first use in this function)

I  am sorry to disturb you again.  do get  the wrong zookeeper source code wrong again ?
